import { NextResponse } from "next/server";
import { connectDB } from "@/lib/databaseConnection";
import OrderModel from "@/models/Order.model";

export async function POST(req) {
  try {
    await connectDB();
    const { orderId } = await req.json();
    
    if (!orderId) {
      return NextResponse.json({ ok: false, message: "Order ID missing" });
    }

    const order = await OrderModel.findById(orderId);
    
    // Agar order na mile
    if (!order) {
      return NextResponse.json({ ok: false, message: "Order not found in database" });
    }

    // Agar usme pehle se AWB ho
    if (order.awbNumber) {
      return NextResponse.json({ ok: false, message: "AWB already exists for this order" }); 
    }

    // Shipmozo ki Get-Order-Detail API ko call karo
    // order.shipmozoOrderId bhej kar try karo
const shipmozoRes = await fetch(`https://shipping-api.com/app/api/v1/get-order-detail/${order.shipmozoOrderId}`, {
      method: "GET",
      headers: {
        "public-key": process.env.SHIPMOZO_PUBLIC_KEY,
        "private-key": process.env.SHIPMOZO_PRIVATE_KEY
      }
    });
    
    const shipmozoData = await shipmozoRes.json();

    if (shipmozoData.result === "1" && shipmozoData.data && shipmozoData.data.awb_number) {
      order.awbNumber = shipmozoData.data.awb_number;
      if (shipmozoData.data.courier_company) {
        order.courierName = shipmozoData.data.courier_company;
      }
      
      await order.save();
      
      return NextResponse.json({ ok: true, message: "AWB Fetched Successfully" });
    } else {
      // API fail hone par ya AWB na milne par error bhejo
      return NextResponse.json({ 
        ok: false, 
        message: shipmozoData.message || "AWB not yet generated by ShipMozo for this order" 
      });
    }
    
  } catch (error) {
    console.error("Fetch AWB Error:", error);
    // Silent true ki jagah actual error bhejo
    return NextResponse.json({ ok: false, message: "Internal server error while fetching AWB" });
  }
}