import { NextResponse } from "next/server";
import { connectDB } from "@/lib/databaseConnection";
import OrderModel from "@/models/Order.model";

export async function POST(req) {
  try {
    await connectDB();
    const { orderId } = await req.json();
    
    if (!orderId) {
      return NextResponse.json({ ok: false, message: "Order ID missing" });
    }

    const order = await OrderModel.findById(orderId);
    
    // Agar order na mile
    if (!order) {
      return NextResponse.json({ ok: false, message: "Order not found in database" });
    }

    // Agar usme pehle se AWB ho
    if (order.awbNumber) {
      return NextResponse.json({ ok: false, message: "AWB already exists for this order" }); 
    }

    // Use shipmozoOrderId for fetching details from ShipMozo
    const fetchId = order.shipmozoOrderId || String(order._id);

    // Shipmozo ki Get-Order-Detail API ko call karo
    const shipmozoRes = await fetch(`https://shipping-api.com/app/api/v1/get-order-detail/${fetchId}`, {
      method: "GET",
      headers: {
        "public-key": process.env.SHIPMOZO_PUBLIC_KEY,
        "private-key": process.env.SHIPMOZO_PRIVATE_KEY
      }
    });
    
    const shipmozoData = await shipmozoRes.json();

    // FIXED: Parse the array structure and nested shipping_details
    if (
      shipmozoData.result === "1" && 
      Array.isArray(shipmozoData.data) && 
      shipmozoData.data.length > 0 &&
      shipmozoData.data[0].shipping_details &&
      shipmozoData.data[0].shipping_details.awb_number
    ) {
      const shippingInfo = shipmozoData.data[0].shipping_details;
      
      order.awbNumber = shippingInfo.awb_number;
      if (shippingInfo.courier_company) {
        order.courierName = shippingInfo.courier_company;
      }
      
      await order.save();
      
      return NextResponse.json({ ok: true, message: "AWB Fetched Successfully" });
    } else {
      // API fail hone par ya AWB na milne par error bhejo
      return NextResponse.json({ 
        ok: false, 
        message: shipmozoData.message || "AWB not yet generated by ShipMozo for this order" 
      });
    }
    
  } catch (error) {
    console.error("Fetch AWB Error:", error);
    return NextResponse.json({ ok: false, message: "Internal server error while fetching AWB" });
  }
}