"use client";

declare global {
  interface Window { gtag?: (...args: any[]) => void; fbq?: (...args: any[]) => void; dataLayer?: any[]; }
}
export type AnalyticsItem={item_id:string;item_name:string;item_category?:string;item_category2?:string;item_variant?:string;price:number;quantity?:number;item_brand?:string};
type MetaEventData=Record<string,unknown>;
const META_EVENT_MAP:Record<string,string>={view_item:"ViewContent",add_to_cart:"AddToCart",remove_from_cart:"RemoveFromCart",begin_checkout:"InitiateCheckout",add_payment_info:"AddPaymentInfo",purchase:"Purchase",add_to_wishlist:"AddToWishlist",search:"Search"};
function makeEventId(prefix:string){const random=typeof crypto!=="undefined"&&"randomUUID"in crypto?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;return `${prefix}-${random}`;}
function getCookie(name:string){if(typeof document==="undefined")return "";const row=document.cookie.split("; ").find(e=>e.startsWith(`${name}=`));return row?decodeURIComponent(row.slice(name.length+1)):"";}
function getStoredUser(){if(typeof window==="undefined")return {};try{const raw=localStorage.getItem("user");const user=raw?JSON.parse(raw):{};return {email:typeof user?.email==="string"?user.email:undefined,phone:typeof user?.phone==="string"?user.phone:undefined,firstName:typeof user?.name==="string"?user.name.split(" ")[0]:undefined,lastName:typeof user?.name==="string"?user.name.split(" ").slice(1).join(" "):undefined,externalId:typeof user?._id==="string"?user._id:typeof user?.id==="string"?user.id:undefined};}catch{return {};}}
function itemsToMetaContents(items:AnalyticsItem[]){return items.map(item=>({id:item.item_id,quantity:item.quantity||1,item_price:Number(item.price)||0}));}
export async function trackMetaEvent(eventName:string,eventData:MetaEventData={},options:{eventId?:string;sendToServer?:boolean}={}){if(typeof window==="undefined")return;const eventId=options.eventId||makeEventId(eventName.toLowerCase());const sendToServer=options.sendToServer!==false;if(typeof window.fbq==="function")window.fbq("track",eventName,eventData,{eventID:eventId});if(!sendToServer)return;const user=getStoredUser();try{await fetch("/api/analytics/meta",{method:"POST",headers:{"Content-Type":"application/json"},keepalive:true,body:JSON.stringify({event_name:eventName,event_id:eventId,event_data:eventData,user_data:user,fbp:getCookie("_fbp"),fbc:getCookie("_fbc"),event_source_url:window.location.href})});}catch{}}
export function trackGAEvent(eventName:string,params:Record<string,unknown>={}){if(typeof window==="undefined")return;if(typeof window.gtag==="function"){window.gtag("event",eventName,params);return;}window.dataLayer=window.dataLayer||[];window.dataLayer.push(["event",eventName,params]);}
export function trackEcommerceEvent(gaEventName:string,items:AnalyticsItem[]=[],options:{value?:number;currency?:string;transactionId?:string;listName?:string;searchTerm?:string;eventId?:string;sendMetaServer?:boolean;extra?:Record<string,unknown>}={}){const currency=options.currency||"INR";const value=Number(options.value??items.reduce((sum,item)=>sum+item.price*(item.quantity||1),0));trackGAEvent(gaEventName,{currency,value,items,...(options.transactionId?{transaction_id:options.transactionId}:{}),...(options.listName?{item_list_name:options.listName}:{}),...(options.searchTerm?{search_term:options.searchTerm}:{}),...(options.extra||{})});const metaEvent=META_EVENT_MAP[gaEventName];if(!metaEvent)return;const metaData:MetaEventData={content_type:"product",value,currency,...(items.length?{content_ids:items.map(i=>i.item_id),contents:itemsToMetaContents(items)}:{}),...(options.extra||{})};if(gaEventName==="search"&&options.searchTerm)metaData.search_string=options.searchTerm;if(gaEventName==="view_item_list"&&options.listName)metaData.content_name=options.listName;void trackMetaEvent(metaEvent,metaData,{eventId:options.eventId,sendToServer:options.sendMetaServer!==false});}
export function trackPageViewMeta(){if(typeof window!=="undefined"&&typeof window.fbq==="function")window.fbq("track","PageView");}
