"use client";
import { useEffect, useMemo, useState } from "react";
import { ChevronDown, SlidersHorizontal, X } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
const priceOptions=[{key:"under500",label:"Under ₹500"},{key:"500-1000",label:"₹500 - ₹1000"},{key:"1000-2000",label:"₹1000 - ₹2000"},{key:"2000-5000",label:"₹2000 - ₹5000"},{key:"above5000",label:"Above ₹5000"}];
interface Props{basePath:string;desktopDrawer?:boolean;desktopOpen?:boolean;onDesktopOpenChange?:(open:boolean)=>void;embedded?:boolean;}
export default function ProductFilterSidebar({basePath,desktopDrawer=false,desktopOpen=false,onDesktopOpenChange,embedded=false}:Props){
 const router=useRouter(),searchParams=useSearchParams();const[showFilter,setShowFilter]=useState(false);const[expanded,setExpanded]=useState<Record<string,boolean>>({features:true,sale:false,price:false});
 const currentPriceRanges=useMemo(()=>searchParams?.get("priceRanges")?.split(",").filter(Boolean)||[],[searchParams]);const currentSpecials=useMemo(()=>({isNewArrival:searchParams?.get("isNewArrival")==="true",isSale:searchParams?.get("isSale")==="true",isBestSeller:searchParams?.get("isBestSeller")==="true"}),[searchParams]);
 const[priceRanges,setPriceRanges]=useState<string[]>(currentPriceRanges);const[specials,setSpecials]=useState(currentSpecials);useEffect(()=>setPriceRanges(currentPriceRanges),[currentPriceRanges]);useEffect(()=>setSpecials(currentSpecials),[currentSpecials]);
 const togglePriceRange=(key:string)=>setPriceRanges(p=>p.includes(key)?p.filter(x=>x!==key):[...p,key]);const toggleSpecial=(key:keyof typeof specials)=>setSpecials(p=>({...p,[key]:!p[key]}));const toggleSection=(key:string)=>setExpanded(p=>({...p,[key]:!p[key]}));
 const buildSearch=()=>{const params=new URLSearchParams();Array.from(searchParams?.entries()||[]).forEach(([key,value])=>{if(["priceRanges","isNewArrival","isSale","isBestSeller","page"].includes(key))return;params.set(key,value);});if(priceRanges.length)params.set("priceRanges",priceRanges.join(","));if(specials.isNewArrival)params.set("isNewArrival","true");if(specials.isSale)params.set("isSale","true");if(specials.isBestSeller)params.set("isBestSeller","true");return params.toString();};
 const applyFilters=()=>{const query=buildSearch();router.push(`${basePath}${query?`?${query}`:""}`);setShowFilter(false);onDesktopOpenChange?.(false);};const clearFilters=()=>{const params=new URLSearchParams();Array.from(searchParams?.entries()||[]).forEach(([key,value])=>{if(["priceRanges","isNewArrival","isSale","isBestSeller","page"].includes(key))return;params.set(key,value);});const query=params.toString();setPriceRanges([]);setSpecials({isNewArrival:false,isSale:false,isBestSeller:false});router.push(`${basePath}${query?`?${query}`:""}`);setShowFilter(false);onDesktopOpenChange?.(false);};
 const selectedCount=priceRanges.length+Number(specials.isNewArrival)+Number(specials.isSale)+Number(specials.isBestSeller);
 const section=(key:string,title:string,children:React.ReactNode,count=0)=><div className="border-b border-[#D7D2C8]"><button type="button" onClick={()=>toggleSection(key)} className="w-full flex items-center justify-between py-4 text-left" aria-expanded={expanded[key]}><span className="text-[13px] font-semibold tracking-[0.01em] text-[#1A1A1A]">{title}{count?` (${count})`:""}</span><ChevronDown size={18} className={`transition-transform duration-200 ${expanded[key]?"rotate-180":""}`} aria-hidden="true"/></button>{expanded[key]&&<div className="pb-4">{children}</div>}</div>;
 const filterContent=<div className="bg-white text-[#1A1A1A]"><div className="mb-1 flex items-center justify-between lg:hidden"><span className="text-sm font-semibold">Filters</span>{selectedCount>0&&<span className="text-xs text-[#1A1A1A]/55">{selectedCount} selected</span>}</div>{section("features","Features",<div className="space-y-3"><label className="flex items-center gap-3 cursor-pointer text-sm"><input type="checkbox" checked={specials.isNewArrival} onChange={()=>toggleSpecial("isNewArrival")} className="h-4 w-4 rounded border-[#CFC9BE] accent-[#AEAA9B]"/><span>New Arrivals</span></label><label className="flex items-center gap-3 cursor-pointer text-sm"><input type="checkbox" checked={specials.isBestSeller} onChange={()=>toggleSpecial("isBestSeller")} className="h-4 w-4 rounded border-[#CFC9BE] accent-[#AEAA9B]"/><span>Best Sellers</span></label></div>,Number(specials.isNewArrival)+Number(specials.isBestSeller))}{section("sale","Sale",<label className="flex items-center gap-3 cursor-pointer text-sm"><input type="checkbox" checked={specials.isSale} onChange={()=>toggleSpecial("isSale")} className="h-4 w-4 rounded border-[#CFC9BE] accent-[#AEAA9B]"/><span>On Sale</span></label>,Number(specials.isSale))}{section("price","Price",<div className="space-y-3">{priceOptions.map(option=><label key={option.key} className="flex items-center gap-3 cursor-pointer text-sm"><input type="checkbox" checked={priceRanges.includes(option.key)} onChange={()=>togglePriceRange(option.key)} className="h-4 w-4 rounded border-[#CFC9BE] accent-[#AEAA9B]"/><span>{option.label}</span></label>)}</div>,priceRanges.length)}<div className="flex gap-2 pt-5"><button type="button" onClick={clearFilters} className="flex-1 border border-[#1A1A1A] bg-white px-3 py-2.5 text-xs font-semibold uppercase tracking-wider hover:bg-[#FAF7F2]">Clear</button><button type="button" onClick={applyFilters} className="flex-1 bg-[#AEAA9B] px-3 py-2.5 text-xs font-semibold uppercase tracking-wider text-white hover:bg-[#969184]">Apply</button></div></div>;
 if(embedded)return filterContent;
 if(desktopDrawer){if(!desktopOpen)return <button type="button" onClick={()=>onDesktopOpenChange?.(true)} className="inline-flex h-10 items-center gap-2 border border-[#1A1A1A] bg-white px-4 text-sm font-medium text-[#1A1A1A]" aria-label="Open filters"><SlidersHorizontal size={16} aria-hidden="true"/><span>Filter</span></button>;return <aside className="w-[220px] flex-shrink-0 bg-white"><button type="button" onClick={()=>onDesktopOpenChange?.(false)} className="inline-flex h-10 items-center gap-2 border border-[#1A1A1A] bg-white px-4 text-sm font-medium text-[#1A1A1A]"><SlidersHorizontal size={16} aria-hidden="true"/><span>Hide Filter</span></button><div className="mt-4">{filterContent}</div></aside>;}
 return <><button type="button" onClick={()=>setShowFilter(true)} className="w-full flex items-center justify-between gap-2 px-4 py-3 bg-white border border-[#E3D9C9] text-sm font-medium text-[#1A1A1A]" aria-label="Open filters"><span>Filter</span><SlidersHorizontal size={16} aria-hidden="true"/></button>{showFilter&&<><div className="fixed inset-0 z-[60] bg-black/60" onClick={()=>setShowFilter(false)} aria-hidden="true"/><div className="fixed inset-y-0 right-0 z-[70] w-[85vw] max-w-[350px] bg-white flex flex-col shadow-2xl"><div className="flex items-center justify-between p-4 border-b border-gray-100"><h3 className="font-semibold text-lg">Filters</h3><button type="button" aria-label="Close filters" onClick={()=>setShowFilter(false)} className="p-1"><X size={20}/></button></div><div className="flex-1 overflow-y-auto p-4">{filterContent}</div></div></>}</>;
}
